In [22]:
import os
import pandas as pd
from pandas import read_csv, read_excel, DataFrame
from sae import COTSCar
import gurobipy as gp
from gurobipy import GRB
from gurobipy import quicksum as qsum
import numpy as np
from typing import List

import sys
sys.path.append('../')
import saedfsc

Price of the car.

In [23]:
maxProductPrice = 400000

Information about customers

In [24]:
customers = saedfsc.customers['Name'].to_list()
cQty = dict(zip(saedfsc.customers['Name'], saedfsc.customers['Quantity'])) # customer quantities
cPriceFocus = dict(zip(saedfsc.customers['Name'], saedfsc.customers['PriceFocus']))
name_weights_partworth_dict = saedfsc.customers.set_index('Name')['PartworthUtilityWeights'].to_dict()
name_weights_perf_dict = saedfsc.customers.set_index('Name')['PerformanceUtilityWeights'].to_dict()
cWtsPartworth = {c : np.fromstring(name_weights_partworth_dict[c].strip('[]'), sep=',') for c in name_weights_partworth_dict}
cWtsPerf = {c : np.fromstring(name_weights_perf_dict[c].strip('[]'), sep=',') for c in name_weights_perf_dict}

Methods to help compute the market share for each customer type (based on logit model).

In [25]:
def getTotalUtilityForCustomer(car : COTSCar, c : str, utilFn = 'partworth'):
    total_utility = 0
    pricePerf = (maxProductPrice - car.price) / maxProductPrice # Normalized price (0 is best, 1 is worst)
    if utilFn == 'partworth':
        product_utility = car.partworth_objectives(weights=cWtsPartworth[c])[0]
        total_utility += (1-cPriceFocus[c])*product_utility - cPriceFocus[c]*pricePerf
    elif utilFn == 'performance':
        product_utility = car.objectives(weights=cWtsPerf[c])[0]
        total_utility += (1-cPriceFocus[c])*product_utility + cPriceFocus[c]*pricePerf
    return total_utility

def getMarketShare(car : COTSCar, c : str, competitors : List[COTSCar], utilFn = 'partworth'): # based on logit model of demand
    carUtility = getTotalUtilityForCustomer(car, c, utilFn)
    totalCompetitorUtility = sum([getTotalUtilityForCustomer(competitorCar, c, utilFn) for competitorCar in competitors])
    return carUtility / (totalCompetitorUtility + carUtility)

Create a set of competitors.

In [26]:
profitMargin = 0.1
competitors = []
for i in range(3):
    competitorCar = COTSCar()
    competitorCar.price = (1+profitMargin)*competitorCar.cost()
    competitorCar.name = "Competitor Car " + str(i)
    competitors.append(competitorCar)

names = [car.name for car in competitors]
designs = [car.vector for car in competitors]
salesPrices = ['$' + format(car.price, ",.2f") for car in competitors]
costs = ['$' + format(car.cost(), ",.2f") for car in competitors]
competitorsDF = pd.DataFrame({
    'Name': names,
    'Design': designs,
    'SalesPrice': salesPrices,
    'ProductCost': costs
})
competitorsDF

,Name,Design,SalesPrice,ProductCost
0,Competitor Car 0,"[11, 5, 1, 1, 4, 4, 1, 11, 10, 2, 38, 23, 2, 2...","$15,195.75","$13,814.32"
1,Competitor Car 1,"[2, 4, 7, 5, 10, 5, 0, 2, 1, 2, 41, 18, 2, 0, ...","$73,620.37","$66,927.61"
2,Competitor Car 2,"[10, 10, 8, 5, 7, 2, 6, 3, 0, 4, 11, 52, 1, 2,...","$279,880.44","$254,436.76"

## Partworth Utility

Create a random car and compute market share

In [27]:
carDesignVec = [12, 7, 6, 12, 9, 1, 0, 13, 9, 1, 39, 26, 2, 1, 33, 11, 4]
product = COTSCar()
product.vector = carDesignVec
product.price = (1 + profitMargin)*product.cost()
print("OUR CAR:") 
print("Design: ", product.vector)
print("Sales price: $", format(product.price, ",.2f"))
print("Cost: $", format(product.cost(), ",.2f"))

qtys = [cQty[c] for c in customers]
utilities = [getTotalUtilityForCustomer(product, c) for c in customers]
market_shares = [getMarketShare(product, c, competitors) for c in customers]
expected_customer_demand = [getMarketShare(product, c, competitors)*cQty[c] for c in customers]

df = pd.DataFrame({
    'Name': customers,
    'Quantity': qtys,
    'Utility for our car': utilities,
    'Market share': market_shares,
    'Expected demand': expected_customer_demand
})
total_profit = product.price*df['Expected demand'].sum()
print("Total expected profit: $", format(total_profit, ",.2f"))
print("Market information for our car:")
df

OUR CAR:
Design:  [12, 7, 6, 12, 9, 1, 0, 13, 9, 1, 39, 26, 2, 1, 33, 11, 4]
Sales price: $ 100,841.03
Cost: $ 91,673.66
Total expected profit: $ 334,899,165.40
Market information for our car:

,Name,Quantity,Utility for our car,Market share,Expected demand
0,CustomerType1,469,-0.711540,0.209642,98.322002
1,CustomerType2,929,-0.763950,0.264704,245.909898
2,CustomerType3,294,-0.904846,0.239200,70.324662
3,CustomerType4,834,-0.676633,0.230449,192.194106
4,CustomerType5,733,-0.827020,0.216249,158.510834
5,CustomerType6,35,-1.183427,0.282946,9.903102
6,CustomerType7,239,-1.656241,0.317917,75.982152
7,CustomerType8,564,-0.889819,0.221901,125.152054
8,CustomerType9,927,-0.955588,0.222470,206.230037
9,CustomerType10,366,-0.756482,0.207289,75.867759
10,CustomerType11,286,-1.187065,0.188299,53.853539
11,CustomerType12,372,-0.766982,0.266830,99.260837
12,CustomerType13,143,-0.937859,0.265859,38.017784
13,CustomerType14,660,-0.911890,0.234603,154.837955
14,CustomerType15,201,-0.760069,0.261934,52.648814
15,CustomerType16,240,-0.806641,0.257989,61.917327
16,CustomerType17,383,-0.706627,0.192833,73.854941
17,CustomerType18,799,-1.385024,0.372464,297.598457
18,CustomerType19,752,-1.131997,0.247042,185.775872
19,CustomerType20,435,-0.814437,0.232789,101.263370
20,CustomerType21,540,-1.458903,0.373839,201.873032
21,CustomerType22,860,-1.149405,0.265260,228.124012
22,CustomerType23,874,-1.178404,0.312638,273.245251
23,CustomerType24,561,-1.020757,0.286922,160.963006
24,CustomerType25,448,-1.061948,0.177299,79.429744

## Performance Utility

In [28]:
carDesignVec = [12, 7, 6, 12, 9, 1, 0, 13, 9, 1, 39, 26, 2, 1, 33, 11, 4]
product = COTSCar()
product.vector = carDesignVec
product.price = (1 + profitMargin)*product.cost()
print("OUR CAR:") 
print("Design: ", product.vector)
print("Sales price: $", format(product.price, ",.2f"))
print("Cost: $", format(product.cost(), ",.2f"))

qtys = [cQty[c] for c in customers]
utilities = [getTotalUtilityForCustomer(product, c, 'performance') for c in customers]
market_shares = [getMarketShare(product, c, competitors, 'performance') for c in customers]
expected_customer_demand = [getMarketShare(product, c, competitors, 'performance')*cQty[c] for c in customers]

df = pd.DataFrame({
    'Name': customers,
    'Quantity': qtys,
    'Utility for our car': utilities,
    'Market share': market_shares,
    'Expected demand': expected_customer_demand
})
total_profit = product.price*df['Expected demand'].sum()
print("Total expected profit: $", format(total_profit, ",.2f"))
print("Market information for our car:")
df

OUR CAR:
Design:  [12, 7, 6, 12, 9, 1, 0, 13, 9, 1, 39, 26, 2, 1, 33, 11, 4]
Sales price: $ 27,051.26
Cost: $ 24,592.06
Total expected profit: $ 82,782,719.25
Market information for our car:

,Name,Quantity,Utility for our car,Market share,Expected demand
0,CustomerType1,469,1.717565,0.222605,104.401734
1,CustomerType2,929,1.006846,0.295391,274.418532
2,CustomerType3,294,1.361066,0.237104,69.708613
3,CustomerType4,834,1.404835,0.232907,194.244375
4,CustomerType5,733,1.250322,0.242198,177.530827
5,CustomerType6,35,1.855804,0.221871,7.765502
6,CustomerType7,239,0.987920,0.191262,45.711725
7,CustomerType8,564,1.059495,0.258637,145.871347
8,CustomerType9,927,1.327682,0.217489,201.612205
9,CustomerType10,366,1.628393,0.221076,80.913985
10,CustomerType11,286,1.756204,0.199432,57.037647
11,CustomerType12,372,0.954140,0.299820,111.533133
12,CustomerType13,143,1.164765,0.208601,29.830008
13,CustomerType14,660,1.310811,0.214795,141.764498
14,CustomerType15,201,0.940916,0.304091,61.122337
15,CustomerType16,240,1.053890,0.269963,64.791042
16,CustomerType17,383,1.433595,0.235662,90.258636
17,CustomerType18,799,2.218263,0.217012,173.392878
18,CustomerType19,752,1.784765,0.223140,167.801638
19,CustomerType20,435,1.210502,0.265115,115.325224
20,CustomerType21,540,1.236177,0.207824,112.225144
21,CustomerType22,860,1.661868,0.230200,197.971938
22,CustomerType23,874,1.464474,0.220867,193.037326
23,CustomerType24,561,1.161772,0.260620,146.207897
24,CustomerType25,448,2.250308,0.213701,95.738010